Just a hack to overcome
1) Magento\Test\Php\LiveCodeTest::testCodeStyle
TypeError: strlen() expects parameter 1 to be string, null given
/home/travis/build/orlangur/magento2/dev/tests/static/framework/Magento/Sniffs/Annotation/MethodArgumentsSniff.php:667
/home/travis/build/orlangur/magento2/dev/tests/static/framework/Magento/Sniffs/Annotation/MethodArgumentsSniff.php:630
/home/travis/build/orlangur/magento2/dev/tests/static/framework/Magento/Sniffs/Annotation/MethodArgumentsSniff.php:519
/home/travis/build/orlangur/magento2/dev/tests/static/framework/Magento/Sniffs/Annotation/MethodArgumentsSniff.php:596
/home/travis/build/orlangur/magento2/vendor/squizlabs/php_codesniffer/src/Files/File.php:497
/home/travis/build/orlangur/magento2/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php:91
/home/travis/build/orlangur/magento2/vendor/squizlabs/php_codesniffer/src/Runner.php:585
/home/travis/build/orlangur/magento2/vendor/squizlabs/php_codesniffer/src/Runner.php:394
/home/travis/build/orlangur/magento2/vendor/squizlabs/php_codesniffer/src/Runner.php:114
/home/travis/build/orlangur/magento2/dev/tests/static/framework/Magento/TestFramework/CodingStandard/Tool/CodeSniffer.php:106
/home/travis/build/orlangur/magento2/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php:274